name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build Docker image (includes npm install & npm run build inside Dockerfile)
      - name: Build Docker image
        run: docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/foodie-movie:latest .

      # 4. Push Docker image to DockerHub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/foodie-movie:latest
